import { Page } from "@components/shared";
import { FC } from "react";

const DashboardPage: FC = () => {
  return (
    <Page title="Dashboard" info="Dashboard Page">
      DashboardPage 
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Provident totam animi sapiente cumque, ratione, sint fugit in perferendis inventore culpa excepturi quos ex laboriosam. Quia sed aliquam ad magni amet!
      Laborum labore reprehenderit odio doloremque voluptates iusto, asperiores sapiente esse cumque, dignissimos autem tenetur dolores, fuga corrupti accusamus enim sequi sunt magnam expedita? Maiores incidunt quasi, ad commodi quis laborum!
      Nisi fugit minima quisquam sint velit explicabo cum minus ex? Voluptas eaque amet saepe vel magnam rem ut dolore delectus commodi minus? Consequatur autem id dignissimos velit voluptatem assumenda recusandae!
      Qui dignissimos tempora minima aperiam culpa explicabo, in non similique dicta eveniet, fuga quasi corrupti eum quaerat maiores nemo alias voluptatem. Sequi quidem voluptatibus necessitatibus praesentium labore harum nobis ad.
      Eos repellat debitis placeat vitae ut, aut doloribus optio sint illo et. Eos reiciendis ut soluta a labore perspiciatis, aperiam nobis ratione officia voluptatem nulla odio nesciunt inventore, ipsa rerum.
      Culpa voluptatum ea corrupti delectus quos ad voluptates quia quaerat amet sunt. Ab aliquam praesentium quas aliquid quasi, sapiente, natus hic corrupti mollitia quis adipisci. Eum quas quae quod saepe!
      Ipsa possimus consequatur nihil laudantium debitis mollitia animi beatae architecto eveniet omnis! Itaque tempore eligendi debitis repudiandae. Animi aliquid inventore saepe, sint ullam delectus dolores, quaerat sunt natus, itaque quasi?
      Corporis nesciunt, maxime amet aut dolor obcaecati rem exercitationem, incidunt error officiis sapiente, fuga repudiandae ratione? Quis, cum tempora laborum architecto sapiente suscipit ut incidunt commodi impedit nesciunt cumque ratione.
      Consequuntur placeat dicta, aliquam labore laudantium sapiente ipsa ducimus non eius laboriosam totam obcaecati repudiandae expedita sequi in, aut perferendis, et natus fugiat iste vel! Dolore incidunt deserunt magnam commodi.
      Ex sint velit debitis, eos necessitatibus maxime recusandae assumenda odit quas provident totam ipsum. Laborum exercitationem neque beatae inventore, expedita quibusdam, ipsa velit vero adipisci in soluta dolores. Quis, eaque!
      Itaque sapiente, suscipit amet sed similique nam voluptates repellat fugiat aut expedita dignissimos maxime animi magnam alias ab tempore rem, eius non at perspiciatis aspernatur. Dolore ut eum accusantium magnam.
      Quae ratione illo molestiae maxime praesentium officiis asperiores saepe vitae incidunt omnis est officia quia, quo, expedita id recusandae fuga distinctio blanditiis iste nemo. Recusandae maxime accusamus optio quam doloremque.
      Est ipsa neque debitis sapiente, impedit fugit atque suscipit similique exercitationem dolor at in dolores accusamus eligendi veniam itaque nisi sed. Cum et consectetur ducimus dolore officiis? Accusamus, sapiente quas?
      Dolorem impedit maiores laudantium, fugit ipsam atque repudiandae, quod a illo, eveniet reiciendis! Itaque, ipsa atque obcaecati nesciunt autem facilis explicabo eveniet totam officiis voluptas placeat ducimus nulla numquam ipsam!
      Impedit quibusdam unde natus repudiandae! At accusamus veniam labore doloribus officia ea ab beatae est asperiores iusto dicta, fuga dignissimos, repellat tempora perferendis. Obcaecati dolore quos at corrupti est iste?
      Dolor laborum corrupti necessitatibus asperiores, est culpa accusantium ea odio earum eveniet laudantium ad labore corporis temporibus sequi quidem architecto ut veritatis maiores fuga. At vero dignissimos adipisci facere a!
      Animi provident repudiandae quod in consectetur quasi consequuntur est reprehenderit. Tenetur suscipit velit at, amet quisquam assumenda est cumque quam sit, asperiores quo. Cupiditate molestias tempore accusamus provident maxime nesciunt.
      Ad nostrum, velit id repellendus dolores earum qui necessitatibus deserunt exercitationem reiciendis neque nisi voluptatibus cumque asperiores. Temporibus, aut placeat! Nisi at provident pariatur rem non quisquam praesentium, aut voluptatum?
      Maxime cupiditate quam ipsa similique delectus quibusdam! Ea sequi nobis, fugit laudantium molestias sint quasi consequuntur repellat in doloribus corrupti neque doloremque pariatur a praesentium beatae id, laboriosam deleniti odit.
      Esse corrupti nisi assumenda quibusdam nulla quidem in voluptates dolores. Repellat cupiditate libero labore delectus veritatis animi? Quo ipsum tempora accusamus. Corporis officia a perferendis iusto aliquid dolore harum porro?
      Ex fugit rerum quae accusantium itaque porro molestias! Officia deleniti, nemo consequatur consequuntur aperiam fugiat? Quaerat qui, fuga deserunt repudiandae labore molestiae veniam vero earum modi. Nihil deserunt perspiciatis enim?
      Doloribus quo quibusdam sit omnis tempora repellat sint dolorum, vero, obcaecati incidunt beatae provident consequuntur adipisci magnam similique reprehenderit illo nesciunt maiores earum exercitationem, culpa velit dolore. Pariatur, officiis quidem.
      Et, pariatur nemo iste iure cupiditate facilis. Repellendus sit sed eos dolore quis minus incidunt autem nulla atque facilis repellat odio, temporibus fugiat consequuntur libero dolorem quibusdam debitis at tempore!
      Molestiae laboriosam nihil quod assumenda pariatur est beatae magnam quo in. Sunt sequi libero veritatis, doloremque dolorem, culpa aliquam a neque ipsum, tempora ex praesentium voluptatibus ut porro ullam repellat.
      Similique, aspernatur iure consectetur provident et autem adipisci explicabo impedit beatae tenetur dolore assumenda quibusdam reprehenderit hic dolorem quisquam quae neque quam recusandae ea, laudantium ullam. Voluptatibus aperiam sequi quidem.
      Dolorum enim a necessitatibus dolores omnis nulla ipsam nihil eius, voluptatem labore illum eum natus, est saepe in nostrum voluptates esse porro! Nesciunt vel consequatur est officia. Perspiciatis, reprehenderit. Nobis!
      Id quas libero doloremque explicabo corrupti laudantium ad itaque incidunt nemo tempora temporibus nam inventore reprehenderit natus nisi est dolores, aliquid labore nulla expedita suscipit! Dolorum maxime possimus beatae pariatur!
      Delectus, libero? Impedit voluptatibus quo aliquam nemo ducimus repellat ipsum iure sit harum earum consequuntur quaerat ipsam, laudantium optio. Reprehenderit cum voluptatum dignissimos rerum ullam adipisci non reiciendis molestiae labore.
      Debitis, quo nisi impedit culpa vel, sint doloribus quidem iste vitae amet quas quia dicta placeat molestias porro veniam quaerat quam! Voluptatum voluptatibus odit cum alias, aspernatur recusandae optio dicta.
      Aut distinctio corporis labore natus perferendis omnis quia in enim nobis? Iusto in, consequatur magni magnam neque cupiditate quasi, quam sapiente tempora itaque accusamus aperiam libero repudiandae quas tempore quibusdam!
      Doloribus eius in, consequuntur quos voluptatem rerum dicta aliquid, tempora accusamus, voluptates odio. Iusto nisi vero dicta fugit voluptas, quod odit quos dolores velit neque officiis eius architecto vitae dolorem!
      Corporis quam velit sit. Numquam sint pariatur corporis odio accusantium incidunt quaerat ab iusto impedit ratione voluptas eius nobis eos sit nostrum voluptatibus asperiores, debitis blanditiis mollitia nihil neque nesciunt.
      Pariatur enim sequi tempore ex, magni dolores possimus sint reprehenderit commodi. Necessitatibus beatae aliquam incidunt doloribus? Dolorum reiciendis sunt cum inventore natus error recusandae facere, aut sed eos dolor amet.
      Recusandae alias vero iure deserunt, molestias voluptas corrupti aut officia incidunt rerum impedit obcaecati eum dolorem minima, at deleniti eius esse unde quaerat voluptates perferendis minus! Officia tenetur dolorum earum.
      Obcaecati voluptatibus, dicta quas iste ducimus ab quia iusto itaque molestias quasi enim id blanditiis error a laudantium aut consectetur non aliquam dignissimos dolorem animi deleniti porro. Numquam, vel nobis.
      Cumque id, blanditiis excepturi fuga totam earum corrupti accusamus culpa nihil facere, possimus dicta quia. Qui, optio. Praesentium facilis velit harum aliquam autem molestias ducimus excepturi, suscipit eveniet error assumenda.
      Sequi possimus qui doloremque voluptates unde, corporis mollitia incidunt maiores cumque natus et quisquam porro reprehenderit molestias tenetur deleniti alias numquam, perferendis rerum. Culpa, aut minus aspernatur deleniti doloremque cumque.
      Voluptate aliquid voluptatum delectus praesentium autem ea sunt neque at? Quae eveniet placeat perspiciatis quis saepe dolorem facere, itaque, explicabo ullam reprehenderit unde inventore ipsam, voluptates animi! Quae, similique eveniet?
      Unde provident ea eaque magni, eos ut corporis dicta nisi, tenetur facere atque ducimus velit eveniet iure dignissimos voluptatem, sunt consequuntur expedita. Nam sequi totam architecto dolorum quibusdam sit recusandae.
      Veniam, dolorum dolor. Recusandae quae in praesentium, quis velit voluptas nihil, nobis quas vero libero nisi impedit sed tempore adipisci maiores numquam nam cumque. Nisi labore sunt ipsam possimus libero?
      Provident soluta doloribus eaque saepe enim odio culpa tempora excepturi, nulla ducimus, nam odit omnis facilis porro nobis quisquam? Vitae quas commodi autem perspiciatis, dolore dignissimos odio maxime magnam magni.
      Blanditiis est ipsam ad suscipit modi illum, necessitatibus reprehenderit corrupti natus repellat aperiam neque doloribus numquam delectus eveniet, voluptatibus nihil iusto, laboriosam in perferendis. Consequuntur et incidunt nobis minima at.
      Nam ratione libero est fugiat error ullam minus eaque! Commodi nobis autem, molestias dolorum nisi excepturi perspiciatis. Necessitatibus, laboriosam exercitationem. Nemo voluptate cupiditate accusamus laboriosam fugiat dolorum rem velit sapiente?
      Consequatur praesentium et incidunt dolores voluptates quo delectus, fugit voluptatem voluptatibus nihil autem iure laudantium. Quasi, facere consequuntur recusandae nisi quisquam eveniet sint sunt id ullam, architecto laboriosam odit hic?
      Consequatur, asperiores cupiditate error ratione, maiores porro eaque officiis voluptate ex veniam eveniet doloremque fugiat cumque enim optio! Cupiditate excepturi minima iste nobis perferendis nisi, deserunt iusto. Corrupti, quidem expedita.
      Accusamus quis at, facilis blanditiis aliquam dolores rem adipisci voluptas ut! Repellat fuga deleniti neque iusto quod in veniam, nam quia, dignissimos vel magni, molestias praesentium obcaecati non consequatur excepturi.
      Libero vel facilis voluptatibus eos veritatis ratione laudantium debitis ut, eum recusandae nemo labore voluptatem iure velit modi sit. Dolorum labore enim quibusdam error reiciendis quisquam fugiat culpa nulla at.
      Obcaecati molestias fugit doloremque veniam ipsam impedit numquam blanditiis totam illum dignissimos, quas, porro assumenda aperiam, atque sint possimus enim. Voluptates nemo harum assumenda sequi rerum explicabo fugiat veritatis corporis.
      Voluptatem natus, quia laborum commodi dolor reprehenderit aperiam asperiores obcaecati perferendis cupiditate mollitia totam sint eum, provident possimus voluptates quaerat consequuntur expedita alias molestiae nulla repellat, in suscipit. Consequuntur, nobis!
      Ducimus, facilis excepturi et quidem, repudiandae molestias totam nemo assumenda ea, illum doloribus maxime cum a tenetur voluptate sequi dolorem deleniti minima. Dicta ipsum autem doloremque ea placeat labore excepturi.
      Quae commodi id corrupti repudiandae quo, dignissimos dolorem minima animi, libero explicabo maxime vero, est asperiores consectetur totam! Quas porro eligendi quibusdam veritatis reprehenderit, natus itaque quidem reiciendis molestias repudiandae.
      Dolore eligendi impedit, aliquid nemo, ipsam placeat sapiente iste et saepe cumque commodi, non dolorem a expedita. Inventore ullam qui consectetur aspernatur, labore, reiciendis cum illo nulla consequuntur, quasi enim!
      Iste voluptas doloremque expedita error, at id voluptatibus vitae laborum. Repudiandae quidem eveniet doloremque reprehenderit itaque. Aut odit fugit quaerat dolorem ipsa deserunt quas ab eum maxime eligendi! Quae, id?
      Pariatur earum aliquam perspiciatis eaque molestiae repellat dolore cumque id et facilis, adipisci reiciendis maxime totam soluta vitae omnis. Provident quia, quisquam unde deleniti maxime suscipit quae et soluta minima.
      Neque praesentium est nobis aspernatur quia dignissimos impedit maxime! Consequatur ex aliquid eaque, aliquam optio inventore perferendis ab fuga excepturi cum est eveniet, cumque esse culpa deleniti, et sint? Asperiores?
      Quos mollitia, corporis error fugit, suscipit vitae non reprehenderit possimus similique ipsam animi maiores cum rerum? Eum, possimus quas, illo atque blanditiis sunt, distinctio voluptates temporibus molestias aliquam esse! Laudantium?
      Molestias, inventore aliquam iusto maiores eum autem soluta possimus labore, temporibus tempora iste dolorem unde! Voluptates expedita quod ab architecto exercitationem distinctio laboriosam placeat odio. Quia consequuntur est excepturi possimus.
      Voluptatibus ratione repellat saepe perspiciatis cum necessitatibus non neque praesentium nihil blanditiis tenetur molestias, iste, quos distinctio laudantium! Assumenda numquam quod magni accusantium sequi illo minima deserunt doloribus laudantium omnis!
      Voluptatum qui molestias incidunt. Quis placeat labore quasi enim minima magni officiis voluptates odit doloribus aliquid optio sequi, facere culpa quod, autem laborum magnam asperiores atque impedit numquam, modi laboriosam!
      Possimus sint laborum dolor? Cum commodi praesentium laboriosam. Voluptate culpa eligendi a? Molestias, temporibus soluta. Animi, cumque quisquam rerum ab repellendus incidunt possimus, magni vitae quos corporis quasi aspernatur magnam?
      Error laboriosam molestias, explicabo ipsa sed laudantium odio repudiandae sequi? Fugiat, aperiam quisquam! Fugit a magnam corrupti rem velit aspernatur quod vel! Corrupti nihil quidem quibusdam. Deleniti facere officiis nam?
      Sit nulla, dolores, unde modi corrupti consequatur iste iusto praesentium temporibus eos placeat laborum, natus reprehenderit asperiores qui soluta facilis? Blanditiis asperiores aliquam perferendis recusandae animi quia molestias? Fugiat, qui?
      Eaque in repudiandae nam distinctio enim illum ab suscipit tenetur sed aperiam sunt temporibus, nobis voluptatem minus, consequuntur accusamus et deleniti numquam dolorem aliquid quae. Mollitia iure minus quam quidem!
      Est at inventore delectus doloribus laboriosam. Labore possimus mollitia sit iure aperiam temporibus iste tempore voluptates laudantium voluptatum similique aliquid corrupti incidunt, recusandae reprehenderit soluta omnis amet voluptate sint. Officiis.
      Nisi dolore fugiat repellendus illum ad, sequi eligendi cumque accusantium tempore illo quibusdam eius aspernatur officiis alias est ut cum iusto neque hic, quam fugit pariatur ullam ab facere? Facere.
      Quis similique in laudantium sequi consectetur nesciunt, expedita ipsam facere ratione quaerat vero neque alias distinctio tenetur voluptas animi impedit optio nihil quae voluptates ipsa quibusdam consequatur. Optio, odit tenetur.
      Autem ex quod reiciendis omnis nam et, perferendis tempore quidem harum nostrum a numquam est fugit quasi repellat illo ab reprehenderit odit id, impedit aspernatur ea obcaecati. Dolore, error nostrum!
      Expedita veritatis modi soluta magni consequatur? Porro accusamus quo quasi alias. Similique ex totam obcaecati assumenda blanditiis ipsa dignissimos! Aut, possimus architecto! Cumque eaque cum aliquam impedit voluptatem? Ea, itaque?
      Sequi tenetur laborum in laboriosam, quaerat reiciendis aliquid a. Neque earum repudiandae, nesciunt libero officia molestiae ea id asperiores vero hic, odit quam modi commodi tempore? Facilis ex doloribus voluptatibus!
      Quaerat sit asperiores, praesentium exercitationem et sequi nesciunt beatae laboriosam perspiciatis animi aspernatur modi maxime obcaecati quia aliquid iste tempora. Veritatis quod quis, reprehenderit labore quasi necessitatibus excepturi iure omnis.
      Consequatur rerum quos voluptates, reiciendis velit doloremque cumque ex blanditiis soluta reprehenderit tempora explicabo facilis aperiam. Iure eos perspiciatis, doloribus excepturi, voluptatem obcaecati expedita facere at quod accusamus laborum. Iusto?
      Quod voluptatibus consequatur veniam eos a libero adipisci voluptatum excepturi ab quam consequuntur asperiores eveniet, deserunt quisquam quia facere, numquam dolorum accusantium temporibus, ex rerum sequi iusto nam. Ipsam, laboriosam!
      Aliquid optio facilis, perferendis molestias quas recusandae delectus error ipsum quod porro animi doloribus alias atque sunt voluptate aliquam vitae perspiciatis excepturi ipsa iusto neque velit magni labore sit. Doloremque.
      Illo suscipit quas exercitationem nisi quisquam, sapiente incidunt similique alias laboriosam officiis quam atque molestias ad placeat repellendus asperiores, minima expedita! Nihil ut dolorem porro iste harum velit quasi dolorum.
      Mollitia ad harum esse nisi quisquam laborum perspiciatis, itaque natus? Tenetur perferendis laudantium voluptatibus nulla neque est hic, odit, debitis, obcaecati harum quasi! Et esse autem architecto similique accusamus quod.
      Perferendis sunt fugit architecto eligendi facilis nesciunt corrupti in doloremque expedita quisquam optio deleniti iusto, excepturi, placeat vel facere dolorum, delectus a. Nemo, fugiat nisi. Est dolorem labore quos ipsum.
      Illo expedita provident iusto nisi tenetur neque maiores nihil dolor, vitae quibusdam quidem, dicta qui magni repudiandae in quod obcaecati dignissimos odit voluptas? Est et, quae rerum illum veritatis nisi?
      Mollitia magnam eos impedit iusto officia dolores, quidem consequatur odio, quas suscipit alias laboriosam? Saepe accusamus vel ut ullam ipsam similique iure, explicabo aut, repellat quas nihil inventore quo eligendi.
      Fuga, necessitatibus placeat, autem voluptate qui facere error labore expedita distinctio, quam alias exercitationem. Aliquid quam iure reiciendis accusantium ratione magni illo quod, nostrum rerum omnis velit soluta atque laudantium.
      Repudiandae, architecto? Libero corrupti voluptatibus nihil? Excepturi, fugiat. Molestias veniam architecto, consequatur magni nostrum saepe aspernatur dicta eligendi expedita voluptate nesciunt a dignissimos possimus hic error! Quisquam dolorem nulla iste?
      Sint ex eligendi quidem molestias? Minima hic provident magni recusandae quas! Asperiores facere quaerat quibusdam aliquid omnis magnam placeat. Asperiores, unde. Quaerat obcaecati enim temporibus dignissimos veniam voluptate culpa facilis.
      Rerum ea enim minus reprehenderit labore cupiditate mollitia harum officia, pariatur sapiente ipsum, aperiam aspernatur. Eligendi repudiandae in aliquid iste minima officia mollitia harum nemo recusandae, natus delectus iusto. Consequuntur!
      Sapiente nulla explicabo quibusdam omnis distinctio alias et molestiae excepturi tempora obcaecati. Soluta distinctio doloremque doloribus, blanditiis nam totam dolor deleniti eos voluptate non optio atque excepturi tenetur illo iusto!
      Mollitia cumque ipsa cupiditate labore at rerum sunt distinctio ullam nulla deleniti minima a, facilis odio perferendis eius excepturi quia dolore adipisci, nemo neque, quae consequatur optio molestiae. Iste, voluptates!
      Nobis, magni aperiam. Corrupti odit quasi excepturi quod dolorum laboriosam facere ipsa itaque adipisci nostrum debitis minima, magnam ut non officia repellendus nisi porro, ipsum vitae. Deserunt laudantium veniam eligendi?
      Nesciunt repellat perferendis placeat perspiciatis optio modi rerum? Perspiciatis aliquam iusto eius tempore enim voluptate cum rem, natus dignissimos corrupti inventore perferendis nobis debitis minima harum doloremque, eaque itaque ipsa.
      At aspernatur sint rerum incidunt officiis, non, expedita accusantium quae dolorem fuga minus! Vel provident doloremque quidem ea, recusandae aperiam eveniet veniam, quae libero neque temporibus similique? Eaque, ad suscipit.
      Nesciunt repellendus vel fugit eius architecto odio similique corrupti dignissimos facilis odit nam amet eligendi enim et commodi, quaerat ex ipsa repellat pariatur dolorem sed exercitationem ut. Libero, explicabo nihil!
      Sapiente quas perspiciatis odio dolorem vero? Doloremque assumenda cum tempore, expedita distinctio debitis nam nobis iste nostrum maxime culpa optio magnam nulla laboriosam, impedit ducimus amet inventore provident magni recusandae.
      Quaerat earum odio nemo pariatur vel? Aliquid nesciunt rem quos, quod deserunt voluptates ullam nobis et vero cumque deleniti voluptatum aliquam ex id quas optio debitis ratione veniam neque doloremque.
      Eum cupiditate dolorum ratione sint? Fugiat eligendi aut harum eos ratione eius, autem placeat recusandae quos! Ratione culpa ipsam, voluptas modi dolore ipsa minima repellendus cum, ducimus, officia ex laboriosam.
      Optio repellat corrupti eveniet qui dolorum fugiat dolore dignissimos molestias ducimus aliquid laudantium minus, asperiores alias. Sapiente aliquid fuga similique aspernatur unde ducimus laudantium officiis aliquam! Dolorem dolorum ipsum culpa.
      Dolore sequi hic vero tempore! Iste libero provident doloribus beatae culpa maxime voluptate aliquid magni voluptatibus quis, iusto ipsam aliquam fuga molestiae alias soluta, similique accusantium animi, doloremque hic perferendis?
      Nemo quasi asperiores quidem, reiciendis recusandae voluptas, molestiae nesciunt quibusdam dolor tempore voluptate perspiciatis! Reprehenderit quo ducimus quia ab possimus officiis sint nam quas deserunt, eum mollitia, soluta adipisci fugit.
      Rerum ducimus quod similique illo doloribus blanditiis vero? Magnam, fuga quis ratione ipsam eos dolor libero temporibus magni ipsa sapiente cupiditate quam quibusdam, rerum aperiam dignissimos minima suscipit animi sunt?
      Qui similique ut doloribus distinctio vel fuga minima obcaecati temporibus sequi. Odit iusto error possimus, aliquam autem provident quae eos sint tempora consectetur fuga quisquam dolore dolorum obcaecati esse. Nisi!
      Nisi magnam quo expedita temporibus aliquam minus perspiciatis officia. Nesciunt officia harum delectus repellendus quaerat sequi, eum fugiat consequuntur optio a, doloribus quod minima cupiditate corporis, labore mollitia ratione vitae?
      Placeat facere laborum nostrum commodi error fuga nulla dolores maxime repellendus. Tempore ipsum nemo veniam laudantium, tenetur deserunt dolorem nobis perferendis quae consequatur id quia dolor? Voluptates esse ducimus accusantium.
      Corporis, commodi esse praesentium, expedita blanditiis eveniet asperiores ut corrupti minima dolores eaque iure beatae. Deleniti, eos laborum. Doloremque tenetur quia dicta quod tempora obcaecati impedit itaque omnis inventore nihil.
      Illo, sequi adipisci voluptatum mollitia cupiditate a! Reprehenderit et obcaecati cumque! At, asperiores facere dolores qui, sed sunt ea debitis sit eligendi tempore totam earum distinctio saepe voluptate ullam quo.
    </Page>
  );
};

export default DashboardPage;
